trigger:
- feature/creating-aws-infrastructure
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Maven@3
  displayName: 'MavenFase'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test package'
    #options: '-X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'JwtAwsLab'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    jdkVersionOption: 1.11
- task: PublishBuildArtifacts@1
  displayName: 'ArtifactFase'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'JwtAwsLabArtifact'
    publishLocation: 'Container'
- task: CmdLine@2
  displayName: 'Listingfase'
  inputs:
    script: |
      echo Listing files
      ls
    workingDirectory: '$(System.DefaultWorkingDirectory)/target'
- task: DownloadSecureFile@1
  displayName: SecureFileFase
  name: cred
  inputs:
    secureFile: 'mtr_dev_usr_accessKeys.csv'
- task: CmdLine@2
  displayName: 'CheckingSecureFileFase'
  inputs:
    script: |
      echo Printing secure file path
      
      echo $(cred.secureFilePath)
      
      echo Printing secure file content
      
      cat $(cred.secureFilePath)
      
      echo Printing enviroment variable
      
      cd $AWS_PROFILE
- task: CmdLine@2
  displayName: 'CheckingAWSProfileFase'
  inputs:
    script: |
      echo Setting aws profile
      
      aws configure import --csv file://$(cred.secureFilePath)
      
      aws configure list-profiles